# Generated by Django 4.2.7 on 2025-09-22 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_courseauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseauditlog',
            name='affected_objects',
            field=models.JSONField(blank=True, help_text='IDs y tipos de objetos afectados por la operación', null=True),
        ),
        migrations.AddField(
            model_name='courseauditlog',
            name='new_state',
            field=models.JSONField(blank=True, help_text='Estado completo del objeto después de la operación', null=True),
        ),
        migrations.AddField(
            model_name='courseauditlog',
            name='operation_details',
            field=models.JSONField(blank=True, help_text='Detalles específicos de la operación realizada', null=True),
        ),
        migrations.AddField(
            model_name='courseauditlog',
            name='previous_state',
            field=models.JSONField(blank=True, help_text='Estado completo del objeto antes de la operación', null=True),
        ),
        migrations.AddField(
            model_name='courseauditlog',
            name='session_key',
            field=models.CharField(blank=True, help_text='Clave de sesión del usuario', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='courseauditlog',
            name='user_agent_parsed',
            field=models.JSONField(blank=True, help_text='Información parseada del navegador y sistema operativo', null=True),
        ),
        migrations.AlterField(
            model_name='courseauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courseauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
