# Generated by Django 4.2.7 on 2025-09-24 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_courseauditlog_affected_objects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(help_text='Descripción general del temario')),
                ('objectives', models.TextField(help_text='Objetivos de aprendizaje del curso')),
                ('requirements', models.TextField(blank=True, help_text='Requisitos previos o materiales necesarios')),
                ('target_audience', models.TextField(blank=True, help_text='Audiencia objetivo del curso')),
                ('methodology', models.TextField(blank=True, help_text='Metodología de enseñanza')),
                ('evaluation_criteria', models.TextField(blank=True, help_text='Criterios de evaluación')),
                ('resources', models.TextField(blank=True, help_text='Recursos adicionales y bibliografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temario de Curso',
                'verbose_name_plural': 'Temarios de Cursos',
            },
        ),
        migrations.CreateModel(
            name='SyllabusModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del módulo', max_length=200)),
                ('description', models.TextField(help_text='Descripción del módulo')),
                ('order', models.PositiveIntegerField(help_text='Orden del módulo en el temario')),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Duración estimada en horas')),
                ('learning_objectives', models.TextField(blank=True, help_text='Objetivos específicos del módulo')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.coursesyllabus')),
            ],
            options={
                'verbose_name': 'Módulo de Temario',
                'verbose_name_plural': 'Módulos de Temario',
                'ordering': ['order'],
                'unique_together': {('syllabus', 'order')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.CharField(blank=True, help_text='Categorías del curso separadas por comas (ej: programación, web, backend)', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento aplicable (0-100)'),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de finalización del curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, help_text='Fecha de fin del período de inscripción', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio del período de inscripción', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de estudiantes que pueden inscribirse', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Cursos que deben completarse antes de inscribirse en este curso', related_name='dependent_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del curso en la moneda local', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('one_time', 'Pago único'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('lifetime', 'De por vida')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas del curso separadas por comas', max_length=500),
        ),
        migrations.AddField(
            model_name='coursesyllabus',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.course'),
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del tema', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción del tema')),
                ('order', models.PositiveIntegerField(help_text='Orden del tema dentro del módulo')),
                ('is_practical', models.BooleanField(default=False, help_text='Indica si es un tema práctico')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.syllabusmodule')),
            ],
            options={
                'verbose_name': 'Tema de Módulo',
                'verbose_name_plural': 'Temas de Módulos',
                'ordering': ['order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la reseña', max_length=200)),
                ('content', models.TextField(help_text='Contenido de la reseña')),
                ('is_approved', models.BooleanField(default=False, help_text='Reseña aprobada por moderador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña de Curso',
                'verbose_name_plural': 'Reseñas de Cursos',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación del 1 al 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Curso',
                'verbose_name_plural': 'Calificaciones de Cursos',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
